//! V2 payload binding: the witness commitment as a component of the payload hash.
//!
//! For `payload_kind == 2` the sequencer forms
//!
//! ```text
//! payload_plain_hash = SHA-256( DOMAIN ‖ C_bytes ‖ rest_hash )
//! ```
//!
//! where `C` is the salted Rescue witness commitment the circuit already
//! boundary-asserts, and `rest_hash` is SHA-256 over the payload with the amount
//! and salt removed. The verifier recomputes this natively. Because the AIR
//! already proves `C = Rescue(amount ‖ salt)` and `amount <= L`, binding `C` into
//! the payload hash makes the proved amount *the amount on the event* — with no
//! circuit change and no signed artifact. `docs/AMOUNT_BINDING_DESIGN.md` has
//! the argument; `docs/SOUNDNESS.md` states the resulting statement.
//!
//! `C_bytes` is the four limbs as 8-byte big-endian words, the same convention
//! as `witness_commitment_u64_to_hex`.

use crate::hash::Hash256;
use crate::public_inputs::{CompliancePublicInputs, PublicInputsError};

/// Domain separator for the V2 payload hash.
pub const PAYLOAD_V2_DOMAIN: &[u8] = b"STATESET_VES_PAYLOAD_V2";

/// `payload_kind` value under which [`validate_payload_v2_binding`] applies.
pub const PAYLOAD_KIND_V2: u32 = 2;

/// Serialize a witness commitment as 32 bytes: four 8-byte big-endian words.
pub fn witness_commitment_bytes(c: &[u64; 4]) -> [u8; 32] {
    let mut out = [0u8; 32];
    for (i, v) in c.iter().enumerate() {
        out[i * 8..i * 8 + 8].copy_from_slice(&v.to_be_bytes());
    }
    out
}

/// Compute `payload_plain_hash` for a V2 event from `C` and `rest_hash`.
///
/// This is the function the sequencer must implement byte-for-byte; the KAT in
/// this module pins it.
pub fn payload_plain_hash_v2(c: &[u64; 4], rest_hash: &[u8; 32]) -> Hash256 {
    let mut data = [0u8; 64];
    data[..32].copy_from_slice(&witness_commitment_bytes(c));
    data[32..].copy_from_slice(rest_hash);
    Hash256::sha256_with_domain(PAYLOAD_V2_DOMAIN, &data)
}

/// For `payload_kind == 2`, require that `payload_plain_hash` really is
/// `SHA-256(domain ‖ C ‖ restHash)` for the commitment `C` the proof was
/// verified against. A no-op for other payload kinds.
pub fn validate_payload_v2_binding(
    inputs: &CompliancePublicInputs,
    c: &[u64; 4],
) -> Result<(), PublicInputsError> {
    if inputs.payload_kind != PAYLOAD_KIND_V2 {
        return Ok(());
    }
    let rest_hex = inputs.rest_hash.as_deref().ok_or_else(|| {
        PublicInputsError::PayloadV2Binding(
            "payload_kind is 2 but restHash is absent from the public inputs".to_string(),
        )
    })?;
    let rest = Hash256::from_hex(rest_hex)
        .map_err(|e| PublicInputsError::PayloadV2Binding(format!("restHash: {e}")))?;
    let expected = payload_plain_hash_v2(c, rest.as_bytes()).to_hex();
    if expected != inputs.payload_plain_hash {
        return Err(PublicInputsError::PayloadV2Binding(format!(
            "payload_plain_hash {} is not SHA-256(domain ‖ C ‖ restHash) = {} for the proved \
             commitment; the proof's amount is not the amount on this event",
            inputs.payload_plain_hash, expected
        )));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Generated by an independent Python implementation:
    /// `sha256(b"STATESET_VES_PAYLOAD_V2" + C_be + bytes([0x11]*32))`.
    #[test]
    fn kat_payload_plain_hash_v2() {
        let c = [1u64, 2, 3, 4];
        assert_eq!(
            hex::encode(witness_commitment_bytes(&c)),
            "0000000000000001000000000000000200000000000000030000000000000004"
        );
        let h = payload_plain_hash_v2(&c, &[0x11; 32]).to_hex();
        assert_eq!(
            h,
            "83074be6285105fbcd4d83dfa233bf5a93e1ca17dfa23b55bf1b8bb9395915de"
        );
    }

    #[test]
    fn commitment_bytes_match_hex_convention() {
        let c = [0xdead_beef_u64, 1, u64::MAX, 7];
        assert_eq!(
            hex::encode(witness_commitment_bytes(&c)),
            crate::public_inputs::witness_commitment_u64_to_hex(&c)
        );
    }
}
