/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Public inputs for compliance proof generation/verification */
export interface JsCompliancePublicInputs {
  /** UUID of the event being proven */
  eventId: string
  /** Tenant ID */
  tenantId: string
  /** Store ID */
  storeId: string
  /** Sequence number of the event */
  sequenceNumber: bigint
  /** Payload kind (event type discriminator) */
  payloadKind: number
  /** SHA-256 hash of plaintext payload (hex64, lowercase) */
  payloadPlainHash: string
  /** SHA-256 hash of ciphertext payload (hex64, lowercase) */
  payloadCipherHash: string
  /** Event signing hash (hex64, lowercase) */
  eventSigningHash: string
  /** Policy identifier (e.g., "aml.threshold") */
  policyId: string
  /** Policy parameters as JSON object */
  policyParams: any
  /** Policy hash (hex64, lowercase) */
  policyHash: string
  /** Optional witness commitment (hex64, lowercase) to bind the proved witness to canonical inputs. */
  witnessCommitment?: string
  /** Optional authorization receipt hash (hex64, lowercase) committed into canonical public inputs. */
  authorizationReceiptHash?: string
}
/** Result of proof generation */
export interface JsComplianceProof {
  /** Raw proof bytes */
  proofBytes: Buffer
  /** SHA-256 hash of proof bytes (hex) */
  proofHash: string
  /** Time taken to generate proof in milliseconds */
  provingTimeMs: number
  /** Size of proof in bytes */
  proofSize: number
  /** Witness commitment (4 x u64 as field elements) */
  witnessCommitment: Array<string>
  /** Witness commitment encoded as 32 bytes (4 x u64 big-endian) and hex-encoded (64 chars). */
  witnessCommitmentHex: string
}
/** Result of proof verification */
export interface JsVerificationResult {
  /** Whether the proof is valid */
  valid: boolean
  /** Time taken to verify in milliseconds */
  verificationTimeMs: number
  /** Error message if verification failed */
  error?: string
  /** Policy ID that was verified */
  policyId: string
  /** Policy limit that was verified against */
  policyLimit: bigint
}
/**
 * Generate a STARK compliance proof for the provided amount witness.
 *
 * @param amount - The amount to prove compliance for (must satisfy the policy constraint)
 * @param publicInputs - Public inputs including event metadata and policy info
 * @param policyType - Policy type: "aml.threshold", "order_total.cap", or "agent.authorization.v1"
 * @param policyLimit - The policy limit (threshold, cap, or maxTotal value)
 * @returns ComplianceProof containing proof bytes and metadata
 *
 * Note: this proves a statement about the supplied `amount` witness. Binding that
 * witness back to encrypted payload contents is the responsibility of the
 * surrounding pipeline, not this library.
 */
export declare function prove(amount: bigint, publicInputs: JsCompliancePublicInputs, policyType: string, policyLimit: bigint): JsComplianceProof
/**
 * Verify a STARK compliance proof
 *
 * @param proofBytes - The raw proof bytes from prove()
 * @param publicInputs - Public inputs (must match those used for proving)
 * @param witnessCommitment - Witness commitment from the proof
 * @returns VerificationResult indicating if proof is valid
 *
 * Malformed public inputs, malformed proof encodings, or witness-commitment binding
 * mismatches are reported as thrown errors rather than `valid = false`.
 */
export declare function verify(proofBytes: Buffer, publicInputs: JsCompliancePublicInputs, witnessCommitment: Array<string>): JsVerificationResult
/**
 * Verify a STARK compliance proof using the witness commitment hex string.
 *
 * This avoids `u64` round-trip issues in JavaScript.
 * Malformed public inputs, malformed proof encodings, or witness-commitment binding
 * mismatches are reported as thrown errors rather than `valid = false`.
 */
export declare function verifyHex(proofBytes: Buffer, publicInputs: JsCompliancePublicInputs, witnessCommitmentHex: string): JsVerificationResult
/** Verify an `agent.authorization.v1` proof against a canonical authorization receipt. */
export declare function verifyAgentAuthorization(proofBytes: Buffer, publicInputs: JsCompliancePublicInputs, witnessCommitment: Array<string>, receipt: any): JsVerificationResult
/** Verify an `agent.authorization.v1` proof using the witness commitment hex string. */
export declare function verifyAgentAuthorizationHex(proofBytes: Buffer, publicInputs: JsCompliancePublicInputs, witnessCommitmentHex: string, receipt: any): JsVerificationResult
/**
 * Compute the policy hash for given policy ID and parameters
 *
 * @param policyId - Policy identifier (e.g., "aml.threshold")
 * @param policyParams - Policy parameters as JSON object
 * @returns Policy hash as hex string (64 characters, lowercase)
 */
export declare function computePolicyHash(policyId: string, policyParams: any): string
/**
 * Create policy parameters for AML threshold policy
 *
 * @param threshold - The AML threshold value
 * @returns Policy parameters JSON object
 */
export declare function createAmlThresholdParams(threshold: bigint): any
/**
 * Create policy parameters for order total cap policy
 *
 * @param cap - The order total cap value
 * @returns Policy parameters JSON object
 */
export declare function createOrderTotalCapParams(cap: bigint): any
/**
 * Create policy parameters for agent authorization policy.
 *
 * @param maxTotal - The maximum delegated total
 * @param intentHash - The delegated commerce intent hash (hex64, lowercase recommended)
 * @returns Policy parameters JSON object
 */
export declare function createAgentAuthorizationParams(maxTotal: bigint, intentHash: string): any
