/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Public inputs for compliance proof generation/verification */
export interface JsCompliancePublicInputs {
  /** UUID of the event being proven */
  eventId: string
  /** Tenant ID */
  tenantId: string
  /** Store ID */
  storeId: string
  /** Sequence number of the event */
  sequenceNumber: number
  /** Payload kind (event type discriminator) */
  payloadKind: number
  /** SHA-256 hash of plaintext payload (hex64, lowercase) */
  payloadPlainHash: string
  /** SHA-256 hash of ciphertext payload (hex64, lowercase) */
  payloadCipherHash: string
  /** Event signing hash (hex64, lowercase) */
  eventSigningHash: string
  /** Policy identifier (e.g., "aml.threshold") */
  policyId: string
  /** Policy parameters as JSON object */
  policyParams: any
  /** Policy hash (hex64, lowercase) */
  policyHash: string
}
/** Result of proof generation */
export interface JsComplianceProof {
  /** Raw proof bytes */
  proofBytes: Buffer
  /** SHA-256 hash of proof bytes (hex) */
  proofHash: string
  /** Time taken to generate proof in milliseconds */
  provingTimeMs: number
  /** Size of proof in bytes */
  proofSize: number
  /** Witness commitment (4 x u64 as field elements) */
  witnessCommitment: Array<number>
}
/** Result of proof verification */
export interface JsVerificationResult {
  /** Whether the proof is valid */
  valid: boolean
  /** Time taken to verify in milliseconds */
  verificationTimeMs: number
  /** Error message if verification failed */
  error?: string
  /** Policy ID that was verified */
  policyId: string
  /** Policy limit that was verified against */
  policyLimit: number
}
/**
 * Generate a STARK compliance proof
 *
 * @param amount - The amount to prove compliance for (must be less than policy limit)
 * @param publicInputs - Public inputs including event metadata and policy info
 * @param policyType - Policy type: "aml.threshold" or "order_total.cap"
 * @param policyLimit - The policy limit (threshold or cap value)
 * @returns ComplianceProof containing proof bytes and metadata
 */
export declare function prove(amount: number, publicInputs: JsCompliancePublicInputs, policyType: string, policyLimit: number): JsComplianceProof
/**
 * Verify a STARK compliance proof
 *
 * @param proofBytes - The raw proof bytes from prove()
 * @param publicInputs - Public inputs (must match those used for proving)
 * @param witnessCommitment - Witness commitment from the proof
 * @returns VerificationResult indicating if proof is valid
 */
export declare function verify(proofBytes: Buffer, publicInputs: JsCompliancePublicInputs, witnessCommitment: Array<number>): JsVerificationResult
/**
 * Compute the policy hash for given policy ID and parameters
 *
 * @param policyId - Policy identifier (e.g., "aml.threshold")
 * @param policyParams - Policy parameters as JSON object
 * @returns Policy hash as hex string (64 characters, lowercase)
 */
export declare function computePolicyHash(policyId: string, policyParams: any): string
/**
 * Create policy parameters for AML threshold policy
 *
 * @param threshold - The AML threshold value
 * @returns Policy parameters JSON object
 */
export declare function createAmlThresholdParams(threshold: number): any
/**
 * Create policy parameters for order total cap policy
 *
 * @param cap - The order total cap value
 * @returns Policy parameters JSON object
 */
export declare function createOrderTotalCapParams(cap: number): any
